export const BASE_URL = "https://store.istad.co"


export const ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NzU2ODUyLCJpYXQiOjE3MTQ3NTY0OTIsImp0aSI6IjMwOTg4MjFkZmVlNjRiZTViMjMzMDk5NWI3YTBmNTU1IiwidXNlcl9pZCI6OTd9.yBbz_UimglMq3CDNhGXbVifWLw5PYuICl9fWBlh7z_c"