import type { Metadata } from "next";
import "@/app/globals.css";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import { Suspense } from "react";
import Loading from "./loading";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import { inter, suwannaphum, localCustomFont } from './fonts'
import StoreProvider from "../StoreProvider";
import SessionWrapper from "../SessionWrapper";


export const metadata: Metadata = {
  title: "Vann Commerce",
  description: "Generated by create next app",
  openGraph: {
    title: "Ecommerce website",
    description: "Ecommerce website sell all products",
    images: "https://d1u4v6449fgzem.cloudfront.net/2020/03/The-Ecommerce-Business-Model-Explained.jpg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <SessionWrapper>
      <body className={`${inter.variable} ${suwannaphum.variable} ${localCustomFont.variable}`}>
        <StoreProvider>
          <header>
            <NavbarComponent />
          </header>
          <ErrorBoundary errorComponent={Error}>
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
          </ErrorBoundary>
        </StoreProvider>
      </body>
    </SessionWrapper>
  );
}
